package modelo;
// Generated 2 feb 2022 15:48:22 by Hibernate Tools 5.5.7.Final

/**
 * Datosindice generated by hbm2java
 */
public class Datosindice implements java.io.Serializable {

	private Integer idDatosindice;
	private String codEstacion;
	private String date;
	private String hourGmt;
	private String no2ica;
	private String o3ica;
	private String pm10ica;
	private String pm25ica;
	private String so2ica;
	private String icaestacion;

	public Datosindice() {
	}

	public Datosindice(String codEstacion, String date, String hourGmt) {
		this.codEstacion = codEstacion;
		this.date = date;
		this.hourGmt = hourGmt;
	}

	public Datosindice(String codEstacion, String date, String hourGmt, String no2ica, String o3ica, String pm10ica,
			String pm25ica, String so2ica, String icaestacion) {
		this.codEstacion = codEstacion;
		this.date = date;
		this.hourGmt = hourGmt;
		this.no2ica = no2ica;
		this.o3ica = o3ica;
		this.pm10ica = pm10ica;
		this.pm25ica = pm25ica;
		this.so2ica = so2ica;
		this.icaestacion = icaestacion;
	}

	public Integer getIdDatosindice() {
		return this.idDatosindice;
	}

	public void setIdDatosindice(Integer idDatosindice) {
		this.idDatosindice = idDatosindice;
	}

	public String getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(String codEstacion) {
		this.codEstacion = codEstacion;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getHourGmt() {
		return this.hourGmt;
	}

	public void setHourGmt(String hourGmt) {
		this.hourGmt = hourGmt;
	}

	public String getNo2ica() {
		return this.no2ica;
	}

	public void setNo2ica(String no2ica) {
		this.no2ica = no2ica;
	}

	public String getO3ica() {
		return this.o3ica;
	}

	public void setO3ica(String o3ica) {
		this.o3ica = o3ica;
	}

	public String getPm10ica() {
		return this.pm10ica;
	}

	public void setPm10ica(String pm10ica) {
		this.pm10ica = pm10ica;
	}

	public String getPm25ica() {
		return this.pm25ica;
	}

	public void setPm25ica(String pm25ica) {
		this.pm25ica = pm25ica;
	}

	public String getSo2ica() {
		return this.so2ica;
	}

	public void setSo2ica(String so2ica) {
		this.so2ica = so2ica;
	}

	public String getIcaestacion() {
		return this.icaestacion;
	}

	public void setIcaestacion(String icaestacion) {
		this.icaestacion = icaestacion;
	}

}
