package modelo;
// Generated 2 feb 2022 15:48:22 by Hibernate Tools 5.5.7.Final

import java.math.BigDecimal;

/**
 * EspaciosNaturales generated by hbm2java
 */
public class EspaciosNaturales implements java.io.Serializable {

	private Integer codEspacio;
	private String nombre;
	private String descripcion;
	private BigDecimal latitud;
	private BigDecimal longitud;
	private String codMunicipio;

	public EspaciosNaturales() {
	}

	public EspaciosNaturales(String nombre, String codMunicipio) {
		this.nombre = nombre;
		this.codMunicipio = codMunicipio;
	}

	public EspaciosNaturales(String nombre, String descripcion, BigDecimal latitud, BigDecimal longitud,
			String codMunicipio) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.latitud = latitud;
		this.longitud = longitud;
		this.codMunicipio = codMunicipio;
	}

	public Integer getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(Integer codEspacio) {
		this.codEspacio = codEspacio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public BigDecimal getLatitud() {
		return this.latitud;
	}

	public void setLatitud(BigDecimal latitud) {
		this.latitud = latitud;
	}

	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	public String getCodMunicipio() {
		return this.codMunicipio;
	}

	public void setCodMunicipio(String codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

}
