package modelo;
// Generated 14 ene 2022 15:27:48 by Hibernate Tools 5.5.7.Final

/**
 * EspaciosNaturales generated by hbm2java
 */
public class EspaciosNaturales implements java.io.Serializable {

	private String codEspacio;
	private String nombre;
	private String descripcion;
	private String codMunicipio;

	public EspaciosNaturales() {
	}

	public EspaciosNaturales(String codEspacio, String nombre, String codMunicipio) {
		this.codEspacio = codEspacio;
		this.nombre = nombre;
		this.codMunicipio = codMunicipio;
	}

	public EspaciosNaturales(String codEspacio, String nombre, String descripcion, String codMunicipio) {
		this.codEspacio = codEspacio;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.codMunicipio = codMunicipio;
	}

	public String getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(String codEspacio) {
		this.codEspacio = codEspacio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCodMunicipio() {
		return this.codMunicipio;
	}

	public void setCodMunicipio(String codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

}
