package modelo;
// Generated 27 ene 2022 20:20:27 by Hibernate Tools 5.5.7.Final

/**
 * EstaEn generated by hbm2java
 */
public class EstaEn implements java.io.Serializable {

	private EstaEnId id;

	public EstaEn() {
	}

	public EstaEn(EstaEnId id) {
		this.id = id;
	}

	public EstaEnId getId() {
		return this.id;
	}

	public void setId(EstaEnId id) {
		this.id = id;
	}

}
