package modelo;
// Generated 14 ene 2022 15:27:48 by Hibernate Tools 5.5.7.Final

import java.math.BigDecimal;

/**
 * Estaciones generated by hbm2java
 */
public class Estaciones implements java.io.Serializable {

	private String codEstacion;
	private String nombreEstacion;
	private BigDecimal coordenadaX;
	private BigDecimal coordenadaY;
	private String nomMunicipio;

	public Estaciones() {
	}

	public Estaciones(String codEstacion, String nombreEstacion, BigDecimal coordenadaX, BigDecimal coordenadaY,
			String nomMunicipio) {
		this.codEstacion = codEstacion;
		this.nombreEstacion = nombreEstacion;
		this.coordenadaX = coordenadaX;
		this.coordenadaY = coordenadaY;
		this.nomMunicipio = nomMunicipio;
	}

	public String getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(String codEstacion) {
		this.codEstacion = codEstacion;
	}

	public String getNombreEstacion() {
		return this.nombreEstacion;
	}

	public void setNombreEstacion(String nombreEstacion) {
		this.nombreEstacion = nombreEstacion;
	}

	public BigDecimal getCoordenadaX() {
		return this.coordenadaX;
	}

	public void setCoordenadaX(BigDecimal coordenadaX) {
		this.coordenadaX = coordenadaX;
	}

	public BigDecimal getCoordenadaY() {
		return this.coordenadaY;
	}

	public void setCoordenadaY(BigDecimal coordenadaY) {
		this.coordenadaY = coordenadaY;
	}

	public String getNomMunicipio() {
		return this.nomMunicipio;
	}

	public void setNomMunicipio(String nomMunicipio) {
		this.nomMunicipio = nomMunicipio;
	}

}
