package modelo;
// Generated 27 ene 2022 20:20:27 by Hibernate Tools 5.5.7.Final

/**
 * FavoritosEspacios generated by hbm2java
 */
public class FavoritosEspacios implements java.io.Serializable {

	private FavoritosEspaciosId id;

	public FavoritosEspacios() {
	}

	public FavoritosEspacios(FavoritosEspaciosId id) {
		this.id = id;
	}

	public FavoritosEspaciosId getId() {
		return this.id;
	}

	public void setId(FavoritosEspaciosId id) {
		this.id = id;
	}

}
