package modelo;
// Generated 21 ene 2022 15:37:18 by Hibernate Tools 5.5.7.Final

/**
 * FavoritosEspaciosId generated by hbm2java
 */
public class FavoritosEspaciosId implements java.io.Serializable {

	private int codUsuario;
	private String codEspacio;

	public FavoritosEspaciosId() {
	}

	public FavoritosEspaciosId(int codUsuario, String codEspacio) {
		this.codUsuario = codUsuario;
		this.codEspacio = codEspacio;
	}

	public int getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(int codUsuario) {
		this.codUsuario = codUsuario;
	}

	public String getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(String codEspacio) {
		this.codEspacio = codEspacio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritosEspaciosId))
			return false;
		FavoritosEspaciosId castOther = (FavoritosEspaciosId) other;

		return (this.getCodUsuario() == castOther.getCodUsuario())
				&& ((this.getCodEspacio() == castOther.getCodEspacio())
						|| (this.getCodEspacio() != null && castOther.getCodEspacio() != null
								&& this.getCodEspacio().equals(castOther.getCodEspacio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodUsuario();
		result = 37 * result + (getCodEspacio() == null ? 0 : this.getCodEspacio().hashCode());
		return result;
	}

}
