package modelo;
// Generated 2 feb 2022 15:48:22 by Hibernate Tools 5.5.7.Final

/**
 * Hashes generated by hbm2java
 */
public class Hashes implements java.io.Serializable {

	private String hash;

	public Hashes() {
	}

	public Hashes(String hash) {
		this.hash = hash;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

}
