package modelo;
// Generated 23 ene 2022 21:24:19 by Hibernate Tools 5.5.7.Final

/**
 * ImagenesEspaciosnaturales generated by hbm2java
 */
public class ImagenesEspaciosnaturales implements java.io.Serializable {

	private ImagenesEspaciosnaturalesId id;

	public ImagenesEspaciosnaturales() {
	}

	public ImagenesEspaciosnaturales(ImagenesEspaciosnaturalesId id) {
		this.id = id;
	}

	public ImagenesEspaciosnaturalesId getId() {
		return this.id;
	}

	public void setId(ImagenesEspaciosnaturalesId id) {
		this.id = id;
	}

}
