package modelo;
// Generated 14 ene 2022 15:27:48 by Hibernate Tools 5.5.7.Final

/**
 * ImagenesEspaciosnaturalesId generated by hbm2java
 */
public class ImagenesEspaciosnaturalesId implements java.io.Serializable {

	private String codEspacio;
	private String nombreImagen;

	public ImagenesEspaciosnaturalesId() {
	}

	public ImagenesEspaciosnaturalesId(String codEspacio, String nombreImagen) {
		this.codEspacio = codEspacio;
		this.nombreImagen = nombreImagen;
	}

	public String getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(String codEspacio) {
		this.codEspacio = codEspacio;
	}

	public String getNombreImagen() {
		return this.nombreImagen;
	}

	public void setNombreImagen(String nombreImagen) {
		this.nombreImagen = nombreImagen;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImagenesEspaciosnaturalesId))
			return false;
		ImagenesEspaciosnaturalesId castOther = (ImagenesEspaciosnaturalesId) other;

		return ((this.getCodEspacio() == castOther.getCodEspacio()) || (this.getCodEspacio() != null
				&& castOther.getCodEspacio() != null && this.getCodEspacio().equals(castOther.getCodEspacio())))
				&& ((this.getNombreImagen() == castOther.getNombreImagen())
						|| (this.getNombreImagen() != null && castOther.getNombreImagen() != null
								&& this.getNombreImagen().equals(castOther.getNombreImagen())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodEspacio() == null ? 0 : this.getCodEspacio().hashCode());
		result = 37 * result + (getNombreImagen() == null ? 0 : this.getNombreImagen().hashCode());
		return result;
	}

}
