package modelo;
// Generated 21 ene 2022 15:37:18 by Hibernate Tools 5.5.7.Final

import java.util.Arrays;

/**
 * ImagenesEspaciosnaturalesId generated by hbm2java
 */
public class ImagenesEspaciosnaturalesId implements java.io.Serializable {

	private String codEspacio;
	private byte[] imagen;

	public ImagenesEspaciosnaturalesId() {
	}

	public ImagenesEspaciosnaturalesId(String codEspacio, byte[] imagen) {
		this.codEspacio = codEspacio;
		this.imagen = imagen;
	}

	public String getCodEspacio() {
		return this.codEspacio;
	}

	public void setCodEspacio(String codEspacio) {
		this.codEspacio = codEspacio;
	}

	public byte[] getImagen() {
		return this.imagen;
	}

	public void setImagen(byte[] imagen) {
		this.imagen = imagen;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImagenesEspaciosnaturalesId))
			return false;
		ImagenesEspaciosnaturalesId castOther = (ImagenesEspaciosnaturalesId) other;

		return ((this.getCodEspacio() == castOther.getCodEspacio()) || (this.getCodEspacio() != null
				&& castOther.getCodEspacio() != null && this.getCodEspacio().equals(castOther.getCodEspacio())))
				&& ((this.getImagen() == castOther.getImagen()) || (this.getImagen() != null
						&& castOther.getImagen() != null && Arrays.equals(this.getImagen(), castOther.getImagen())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodEspacio() == null ? 0 : this.getCodEspacio().hashCode());
		int imagenHashcode = 0;
		byte[] imagenProperty = this.getImagen();
		if (imagenProperty != null) {
			imagenHashcode = 1;
			for (int i = 0; i < imagenProperty.length; i++) {
				imagenHashcode = 37 * imagenHashcode + imagenProperty[i];
			}
		}

		result = 37 * result + imagenHashcode;

		return result;
	}

}
