package modelo;
// Generated 28 ene 2022 16:46:24 by Hibernate Tools 5.5.7.Final

/**
 * Municipios generated by hbm2java
 */
public class Municipios implements java.io.Serializable {

	private String codMunicipio;
	private String nombre;
	private String descripcion;
	private String codProvincia;

	public Municipios() {
	}

	public Municipios(String codMunicipio, String nombre, String codProvincia) {
		this.codMunicipio = codMunicipio;
		this.nombre = nombre;
		this.codProvincia = codProvincia;
	}

	public Municipios(String codMunicipio, String nombre, String descripcion, String codProvincia) {
		this.codMunicipio = codMunicipio;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.codProvincia = codProvincia;
	}

	public String getCodMunicipio() {
		return this.codMunicipio;
	}

	public void setCodMunicipio(String codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCodProvincia() {
		return this.codProvincia;
	}

	public void setCodProvincia(String codProvincia) {
		this.codProvincia = codProvincia;
	}

}
