package modelo;
// Generated 23 ene 2022 21:24:19 by Hibernate Tools 5.5.7.Final

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer codUsuario;
	private String nombre;
	private String password;

	public Usuarios() {
	}

	public Usuarios(String nombre, String password) {
		this.nombre = nombre;
		this.password = password;
	}

	public Integer getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(Integer codUsuario) {
		this.codUsuario = codUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
