package modelo;
// Generated 14 ene 2022 15:27:48 by Hibernate Tools 5.5.7.Final

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private int codUsuario;
	private String nombre;
	private String password;

	public Usuarios() {
	}

	public Usuarios(int codUsuario, String nombre, String password) {
		this.codUsuario = codUsuario;
		this.nombre = nombre;
		this.password = password;
	}

	public int getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(int codUsuario) {
		this.codUsuario = codUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
